### ISSUE TITLE
app.yaml does not exist error

### ISSUE THREAD

**Issue by capndave** [actions-hub/gcloud#21]
I'm getting the following on deploy: 
```bash
ERROR: (gcloud.app.deploy) [/github/workspace/app.yaml] does not exist.
```
I noticed [this similar issue](https://github.com/actions-hub/gcloud/issues/1) but the suggestion there does not help in my case (already declared `actions/checkout@v1`). Any ideas?

## .github/workflow/deploy.yaml
```yaml
name: Deploy to Google App Engine
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GCP_CREDENTIALS}}
        with:
          args: app deploy app.yaml
```
