### ISSUE TITLE
WARNING: You do not appear to have access to project [***] or it does not exist.

### ISSUE THREAD

**Issue by ghost** [actions-hub/gcloud#3]
Weirdly this command works:

`gcloud config set project ${{GCLOUD_PROJECT}}`

But when I set the actions it doesn't.

Using your exact example:

```
name: gcloud
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: myProject
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: app deploy app.yaml
```

**Comment by exelban** [comment]
@bgold0 are you sure that provided project_id is correct?

`gcloud config set project ${{GCLOUD_PROJECT}}` - where this command works?

**Comment by ghost** [comment]
I apologize. This warning always shows and isn't reminiscent on whether you have the permissions to deploy or not. My problem was putting the flags before `app deploy app.yaml` and not afterwords so it wasn't actually doing anything.

So this issue doesn't get closed in vain. Here is a working example I used with flags:

```
- uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT}}
          APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_API_KEYFILE}}
        with:
          args: app deploy app.yaml --no-promote --project ${{secrets.GCLOUD_PROJECT}} -v staging
```
