### ISSUE TITLE
Getting the error - module 'OpenSSL.crypto' has no attribute 'sign'

### ISSUE THREAD

**Issue by sabumars** [actions-hub/gcloud#38]
After the change made in this repo to update to DockerFIle
FROM google/cloud-sdk:503.0.0-alpine

We are getting the below error while using this action - actions-hub/gcloud@master

Detect credentials from previous session...
APPLICATION_CREDENTIALS found. Setting up a credentials....
APPLICATION_CREDENTIALS is Base[64](https://github.com/mckesson/copay-clientweb-8146/actions/runs/12277909656/job/34267422282#step:7:65) Encoded
Activated service account credentials for: [***-1@gis-iam-prod-3d6b.iam.gserviceaccount.com]
Previous project id not detected
Updated property [core/project].
module 'OpenSSL.crypto' has no attribute 'sign'
##[debug]Docker Action run completed with exit code 1

**Comment by so-richard-atkins** [comment]
We have also encountered the exact same issue from 11 Dec 2024 11:03:02 GMT

**Comment by surindersutherland** [comment]
We are facing the same issue and are looking for a solution. For now, we have started using the previous version, 502. If anyone finds a solution to this, please let me know. Thanks

**Comment by so-richard-atkins** [comment]
@surindersutherland , incase this is useful to you, we were using github workflow actions for gsutil to copy code to GCS buckets and have decided to work around this problem by refactoring the workflow actions YAML to the following example, which has both got around the problem and reduced the lines of YAML (previously each folder copy statement included the secret, and this new version does not). Would be better to use workload identity, so that's next on the list;

```yaml
    - name: Checkout
      uses: actions/checkout@v4

    - name: gcp authenticate
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ PROJECT_ID }}
        credentials_json: ${{ CREDENTIAL_JSON }}

    - name: copy-folder-name-to-composer
      run: |
        gcloud storage rsync folder_name gs://${{ DAG_BUCKET }}/remote_path --recursive --delete-unmatched-destination-objects
```
