### ISSUE TITLE
Using cache-control as a header fails the build

### ISSUE THREAD

**Issue by kerrmarin** [actions-hub/gcloud#8]
A simple workflow with a step like:
```
      - name: Upload to Google Cloud
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: my-project-id
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLI: gsutil
        with:
          args: -h "Cache-Control:public, max-age=86400" -m cp -r docs/** gs://my-bucket/${{ env.GITHUB_REF_SLUG }}
```

Fails with `CommandException: Invalid command "max-age=86400".`

The same command works if `-h "Cache-Control:public, max-age=86400"` is omitted.

Following the docs [here](https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata) it appears that this should work?
